# Generated by Django 5.1 on 2024-08-15 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TaskDownload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_name", models.CharField(max_length=255)),
                ("class_id", models.CharField(max_length=255)),
                ("dataset_id", models.CharField(max_length=255)),
                ("status", models.CharField(default="Ready", max_length=255)),
                ("priority", models.CharField(default="High", max_length=255)),
                ("duration", models.CharField(default="Indefinitely", max_length=255)),
                ("task_start_time", models.DateTimeField()),
                ("next_run_time", models.DateTimeField()),
                ("last_run_time", models.DateTimeField()),
                ("next_download_file", models.CharField(max_length=255)),
                ("last_download_file", models.CharField(max_length=255)),
                ("enabled", models.BooleanField()),
                ("health", models.CharField(default="Excellent", max_length=255)),
                ("fail_count", models.IntegerField(default=0)),
                ("success_count", models.IntegerField(default=0)),
                ("reset_count", models.IntegerField(default=0)),
                ("attempt_count", models.IntegerField(default=0)),
                (
                    "predecessor_class",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("predecessor_class_id", models.IntegerField(blank=True, null=True)),
                (
                    "successor_class",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("successor_class_id", models.IntegerField(blank=True, null=True)),
                ("created_by", models.CharField(default="root", max_length=255)),
                ("launched_by", models.CharField(default="root", max_length=255)),
                ("retain", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
