# Generated by Django 5.1 on 2024-08-19 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_download", "0003_alter_taskdownload_dataset_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskdownload",
            name="retention_days",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="taskdownload",
            name="retain",
            field=models.BooleanField(),
        ),
    ]
